### ISSUE TITLE
Can’t package in the same folder twice

### ISSUE THREAD

**Issue by MscrmTools** [Danz-maveRICK/PCF-CustomControlBuilder#4]
When creating the package, it seems the package is locked by code. I cannot create the same package twice.
Can’t tell if the lock occurs during package creation or during package import but something definitively locks down the file

**Comment by Danz-maveRICK** [comment]
Once you create a project you cannot create another project in the same directory. Either you have to use another directory or use "Edit existing PCF control" button. I will handle the scenario to check if .pcfproj file already exists and if it does the tool will show appropriate message.

**Comment by MscrmTools** [comment]
I do use « edit existing control ». If I change the name, I can build the package. Then I can use the first name again. 
That’s why I guess something is locked. It says file is already used by another process

**Comment by Danz-maveRICK** [comment]
Try now with new enhancements; I am reading the pcfproj file as well as cdsproj file and prefilling the data. Also the deployment folder if it exists will just rebuild. If you still get error please send me screenshot. Thanks.

**Comment by MscrmTools** [comment]
Works like a charm! Your plugin is really getting interesting!
